### ISSUE TITLE
Question: icon hotspot

### ISSUE THREAD

**Issue by step-** [jun7/rox-filer#146]
Hi jun7,

this isn't an issue report but a set of question about the source code, which you know very well, so I'm hoping you can tell me your opinion, and suggest how to proceed.

Puppy Linux uses ROX pinboard file as Desktop background, and displays a drive bar where each drive is represented as an icon with a hotspot. Clicking the hotspot mounts/unmounts the drive. Note the ROX-Filer draws the icon, since it's part of the pinboard file, but the hotspot is managed by separate shell scripts, since ROX-Filer doesn't support icon hotspots. The script works but is prone to errors, especially when the icon includes text labels, so I want to try to replace the current method.

![xscreenshot-00000](https://cloud.githubusercontent.com/assets/1414102/18028423/37f9fbc2-6c7f-11e6-99d1-b487ff1254f4.png)

 * How difficult do you think it would be to add **pinboard icon hotspots** to rox?
 * Which source files/functions would I need to modify to do it?
 * There should be a way to tell rox where to draw the hotspot relative to the icon top-left origin, and hotspot color (none, crossed green, yellow) and dimensions (width,height)
 * Clicking the icon hotspot should run a given action specified in AppInfo.xml, a shell script, which would re-draw the pinboard icons with their hotspots.

Thank you for considering my questions.

**Comment by jun7** [comment]
Since I don't use pinborad, I haven't any knowledge of pinboard.
May be pinboard's sources are in pinboard.c/.h.
The hotspot in rox called emblem is hard coded in display.c and I suggest don't change it because it is sensitive.

Come to think of it, I heard dtomas makes similar thing.
https://github.com/dtomas/MediaTray
He has edited rox's source a lot, so his approach may serves as a useful reference.

**Comment by step-** [comment]
Thank you.
