### ISSUE TITLE
pinboard icons issue

### ISSUE THREAD

**Issue by mrfricks** [jun7/rox-filer#211]
hi jun7,
in puppy linux we have an event manager to display drive icons dynamically on the rox pinboard. for some reason these display the wrong icon when on the pinboard but they display correctly in the filer (note that in old versions of rox they displayed correctly)
any ideas?
cheers
![snapshot-2020-05-28-14-20-21](https://user-images.githubusercontent.com/1454550/83148080-6a0c2f00-a0f0-11ea-8f8b-377c900a789e.png)

edit:  i should add that these are Appdirs with just Apprun & AppInfo.xml inside

**Comment by JakeSFR** [comment]
Interesting... To reproduce:

1. Create a folder that contains only "AppRun" file (can be empty, but must be executable),
2. Assign an icon to that folder via **right-click -> Set Icon -> Only for the file '/path/to/folder'**,
3. Drag and drop the folder onto the pinboard.

In the filer itself the icon shows up, but on the pinboard it doesn't.

In Fatdog it's not a problem, because we use '.DirIcon' files in drive icons AppDirs.
But in Puppy they seem to be set via **~/.config/rox.sourceforge.net/ROX-Filer/globicons** instead and that's the difference.

**Comment by jun7** [comment]
Thank you JakeSFR that makes sense!

**Comment by jun7** [comment]
Thank you for reporting!

**Comment by JakeSFR** [comment]
Thanks, I can confirm that it works now.

**Comment by mrfricks** [comment]
thanks jun7
working for me as well
